inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/locales/*'
    - 'config/spring.rb'
    - 'db/**/*'
    - 'vendor/**/*'
